cache: yarn
language:
  node_js
node_js:
  - "lts/*"
# Script that is run before the script phase
before_script:
  - yarn
  - yarn build-storybook
script:
  - yarn build
  - yarn test
deploy:
  provider: pages # Tell Travis we want to deploy to Github Pages
  skip-cleanup: true 
  github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
  local_dir: storybook-static # The folder that needs to be deployed
  repo: abrcdf1023/egroup-material # Add your username/project_name here
  target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
  on:
    branch: master # Tell Travis to trigger a deploy only when we push to master